require( "obszczymucha.globals" )
require( "obszczymucha.user-config" )
require( "obszczymucha.common" )
require( "obszczymucha.set" )
require( "obszczymucha.color-overrides" )
require( "obszczymucha.macros" )
require( "obszczymucha.telescope" )
require( "obszczymucha.metals" )
require( "obszczymucha.dap-ui" )
require( "obszczymucha.lua-test" )
require( "obszczymucha.jest-test" )
require( "obszczymucha.rust-test" )
require( "obszczymucha.documentation" )
require( "obszczymucha.debug" )
require( "obszczymucha.cmp" )
require( "obszczymucha.custom-search" )
require( "obszczymucha.autocmds" )
require( "obszczymucha.groovyls" )
require( "obszczymucha.osv" )
require( "obszczymucha.mason" )

if is_wsl then
  require( "obszczymucha.alacritty" )
end
