require( "obszczymucha.common" )
require( "obszczymucha.set" )
require( "obszczymucha.packer" )
require( "obszczymucha.remap" )
require( "obszczymucha.coc" )
require( "obszczymucha.netrw" )
require( "obszczymucha.macros" )
require( "obszczymucha.telescope" )
require( "obszczymucha.metals" )

